### ISSUE TITLE
make: *** No rule to make target 'allocate.o', needed by 'all'.  Stop.

### ISSUE THREAD

**Issue by LukePiszkin** [ugobas/Molecular_clock#1]
When attempting make on "Evol_div.makefile" I am receiving this error:
"make: *** No rule to make target 'allocate.o', needed by 'all'.  Stop."

**Comment by ugobas** [comment]
Solved by adding allocate.c

**Comment by apascualgarcia** [comment]
@ugobas there is a spelling problem, the file was called `Allocate.c` and in the makefile is defined as `allocate.c`, I renamed it and I am able to compile it now, I also pushed the changes. @LukePiszkin could you please confirm that it works now for you?

**Comment by LukePiszkin** [comment]
@apascualgarcia Yes, the code compiles for me now. Thank you.
